import { prisma } from "../../lib/prisma";
import {
  conversationMissionId,
  isConversationMember,
  isMissionaryLocked,
  messageOwner,
} from "../authz";
import { broadcastToConversation } from "../fanout";
import { defineHandler, sendError, type MessageHandlers } from "../protocol";
import { broadcast } from "../registry";
import { conversationScopedSchema, markReadSchema, sendMessageSchema } from "../schemas";

/**
 * Messaging, typing indicators and read receipts.
 *
 * `send_message` was the one handler in the old file that authorized itself
 * properly, and its checks are kept as they were. The other three are new:
 * `typing` and `stop_typing` broadcast into any conversation id, which made the
 * socket a membership oracle for every conversation in the system, and
 * `mark_read` wrote a read receipt for any message id at all.
 */

export const chatHandlers: MessageHandlers = {
  send_message: defineHandler(sendMessageSchema, async (ctx, payload) => {
    const conversationId = payload.conversation_id;

    if (!(await isConversationMember(conversationId, ctx.user.id))) {
      sendError(ctx.socket, "Not a member of this conversation");
      return;
    }

    // Missionary accounts may only talk inside their own mission.
    if (isMissionaryLocked(ctx.user)) {
      const missionId = await conversationMissionId(conversationId);
      if (!missionId || missionId !== ctx.user.missionId) {
        sendError(ctx.socket, "Missionaries can only message within their mission");
        return;
      }
    }

    // One transaction, so a message can never exist without its conversation
    // being bumped to the top of everyone's list.
    const message = await prisma.$transaction(async (tx) => {
      // The id is generated by the database (`@default(uuid())`) rather than
      // passed in, which is why nothing here calls a uuid library.
      const created = await tx.message.create({
        data: {
          conversationId,
          senderId: ctx.user.id,
          type: payload.message_type,
          content: payload.content ?? null,
          mediaUrl: payload.media_url ?? null,
          replyToId: payload.reply_to_message_id ?? null,
        },
        select: { id: true, createdAt: true },
      });
      await tx.conversation.update({
        where: { id: conversationId },
        data: { updatedAt: new Date() },
      });
      return created;
    });

    await broadcastToConversation(conversationId, {
      type: "new_message",
      payload: {
        id: message.id,
        conversation_id: conversationId,
        sender_id: ctx.user.id,
        sender_name: ctx.user.fullName,
        type: payload.message_type,
        content: payload.content ?? null,
        media_url: payload.media_url ?? null,
        created_at: message.createdAt.toISOString(),
        reply_to_message_id: payload.reply_to_message_id ?? null,
      },
    });

    // INTEGRATION: push notification to members who are not currently connected.
    // Old call: notifyConversationMembers(conversationId, senderId, senderName,
    // preview, getOnlineUserIds()). The preview was the message body for text,
    // otherwise "sent a <type>". Recipients are the conversation's members minus
    // the sender minus everyone in getOnlineUserIds().
  }),

  typing: defineHandler(conversationScopedSchema, async (ctx, payload) => {
    if (!(await isConversationMember(payload.conversation_id, ctx.user.id))) {
      sendError(ctx.socket, "Not a member of this conversation");
      return;
    }
    await broadcastToConversation(
      payload.conversation_id,
      {
        type: "user_typing",
        payload: {
          user_id: ctx.user.id,
          user_name: ctx.user.fullName,
          conversation_id: payload.conversation_id,
        },
      },
      ctx.user.id,
    );
  }),

  stop_typing: defineHandler(conversationScopedSchema, async (ctx, payload) => {
    if (!(await isConversationMember(payload.conversation_id, ctx.user.id))) {
      sendError(ctx.socket, "Not a member of this conversation");
      return;
    }
    await broadcastToConversation(
      payload.conversation_id,
      {
        type: "user_stop_typing",
        payload: { user_id: ctx.user.id, conversation_id: payload.conversation_id },
      },
      ctx.user.id,
    );
  }),

  mark_read: defineHandler(markReadSchema, async (ctx, payload) => {
    const message = await messageOwner(payload.message_id);
    if (!message) {
      sendError(ctx.socket, "Message not found");
      return;
    }
    if (!(await isConversationMember(message.conversationId, ctx.user.id))) {
      sendError(ctx.socket, "Not a member of this conversation");
      return;
    }

    await prisma.messageRead.createMany({
      data: [{ messageId: payload.message_id, userId: ctx.user.id }],
      // Re-reading a thread is normal, so an existing receipt is not an error.
      skipDuplicates: true,
    });

    if (message.senderId && message.senderId !== ctx.user.id) {
      broadcast(message.senderId, {
        type: "message_read",
        payload: {
          message_id: payload.message_id,
          reader_id: ctx.user.id,
          conversation_id: message.conversationId,
        },
      });
    }
  }),
};
